#!/usr/bin/env bash
# Regenerate requirements.txt / requirements-dev.txt from uv.lock.
#
# WHY THIS EXISTS
#   Dependencies have one source of truth: pyproject.toml declares the ranges we
#   are compatible with; uv.lock pins the exact versions (including every
#   transitive dep) that we actually ship. Docker installs from the lock
#   (uv sync --frozen --no-dev) and so does CI (uv sync --frozen).
#
#   The requirements*.txt files exist only for the plain-pip convenience path.
#   Exporting them from the lock keeps that path on the SAME versions instead of
#   re-resolving ranges — otherwise pip could install langgraph 1.3 while the
#   images deploy 1.2.10.
#
# USAGE
#   ./scripts/export_requirements.sh          # after any dependency change
#
# BUMPING A DEPENDENCY
#   1. adjust the range in pyproject.toml (only if the new version is outside it)
#   2. uv lock --upgrade-package <name>
#   3. ./scripts/export_requirements.sh
#   4. commit the uv.lock + requirements*.txt diff together, let CI gate it
set -euo pipefail
cd "$(dirname "$0")/.."

if ! command -v uv >/dev/null 2>&1; then
    echo "error: uv is not installed. See https://docs.astral.sh/uv/" >&2
    exit 1
fi

# uv stamps its own "autogenerated by uv" header; we strip it and write our own
# (ours explains the regeneration command, which is the part a reader needs).
strip_uv_header() {
    grep -v '^# This file was autogenerated' | grep -v '^#    uv export'
}

echo "[1/2] requirements.txt      (production, from uv.lock)"
{
    cat <<'HEADER'
# ─────────────────────────────────────────────────────────────────────
# GENERATED FILE — do not hand-edit.
#
# Source of truth is pyproject.toml (ranges = what we're compatible with)
# + uv.lock (exact pins = what we actually ship). This file is exported
# from the lock so the plain-pip path installs the SAME versions that CI
# tests and the Docker images deploy (uv sync --frozen).
#
# Regenerate after any dependency change:
#   ./scripts/export_requirements.sh
#
# To bump a dependency, change the range in pyproject.toml (if needed),
# then: uv lock --upgrade-package <name> && ./scripts/export_requirements.sh
# ─────────────────────────────────────────────────────────────────────
HEADER
    uv export --frozen --no-dev --no-hashes --no-emit-project | strip_uv_header
} > requirements.txt

echo "[2/2] requirements-dev.txt  (production + pytest/ruff, from uv.lock)"
{
    cat <<'HEADER'
# ─────────────────────────────────────────────────────────────────────
# GENERATED FILE — do not hand-edit.  See requirements.txt for the why.
# Dev/test tooling (pytest, ruff) on top of the production set.
# Regenerate: ./scripts/export_requirements.sh
# ─────────────────────────────────────────────────────────────────────
HEADER
    uv export --frozen --no-hashes --no-emit-project | strip_uv_header
} > requirements-dev.txt

echo
echo "Done. Key pins:"
grep -E '^(langgraph|langsmith|litellm|pysisense|fastapi|streamlit)==' requirements.txt | sed 's/^/  /'
